wandb_version: 1

env:
  desc: null
  value:
    step_penalty: 1
    final_reward: 10
    max_action:
    - 2.0
    - 2.0
    - 4.0
    max_steps: 8
    z_step_size: 0.125
    peg_hole_path_file: configs/peg_insertion/3shape_1.5mm.txt
    peg_x_max_offset: 5.0
    peg_y_max_offset: 5.0
    peg_theta_max_offset: 10.0
    marker_interval_range:
    - 1.95
    - 2.15
    marker_rotation_range: 0.1
    marker_translation_range:
    - 1
    - 1
    marker_pos_shift_range:
    - 0.1
    - 0.1
    marker_random_noise: 0.5
    marker_lose_tracking_probability: 0.01
    normalize: false
policy:
  desc: null
  value:
    buffer_size: 200000
    train_freq: 2
    gradient_steps: -1
    learning_starts: 2000
    action_noise: VecNoise(BaseNoise=NormalActionNoise(mu=[0 0 0], sigma=[0.5 0.5
      0.5])), n_envs=4)
    batch_size: 512
    learning_rate: 0.0001
    optimize_memory_usage: false
    ent_coef: auto
    target_update_interval: 1
    target_entropy: auto
    use_sde: false
    sde_sample_freq: -1
    use_sde_at_warmup: false
    policy_kwargs:
      pointnet_in_dim: 4
      pointnet_out_dim: 32
      pointnet_batchnorm: false
      pointnet_layernorm: true
      zero_init_output: true
      use_sde: false
    device: cuda:0
    seed: 0
    tensorboard_log: /home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../training_log/3shape_1.5mm_batch_size_512_lr_0.0001_2024-03-20_16-49-14.316
train:
  desc: null
  value:
    total_timesteps: 500000
    log_interval: 6
    checkpoint_every: 2000
    eval_freq: 2000
    n_eval: 50
    parallel: 4
    seed: 0
    device: cuda:0
    gpu: 0
    name: 3shape_1.5mm_batch_size_512_lr_0.0001
    wandb_name: ManiSkill_ViTac
    emp: {}
cfg:
  desc: null
  value: configs/parameters/peg_insertion_sac.yaml
no_render:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/scripts/train_sac.py
    python_version: 3.10.0
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710924564.768517
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.10.0
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'solutions.policies_sac.SACPolicyForPointFlowEnv'>
device:
  desc: null
  value: cuda:0
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''pointnet_in_dim'': 4, ''pointnet_out_dim'': 32, ''pointnet_batchnorm'':
    False, ''pointnet_layernorm'': True, ''zero_init_output'': True, ''use_sde'':
    False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 500000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: 0
action_noise:
  desc: null
  value: VecNoise(BaseNoise=NormalActionNoise(mu=[0 0 0], sigma=[0.5 0.5 0.5])), n_envs=4)
start_time:
  desc: null
  value: 1710924574726366512
learning_rate:
  desc: null
  value: 0.0001
tensorboard_log:
  desc: null
  value: /home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../training_log/3shape_1.5mm_batch_size_512_lr_0.0001_2024-03-20_16-49-14.316
_last_obs:
  desc: null
  value: "OrderedDict([('gt_offset', array([[-1.8596221, -4.574301 ,  1.9105394],\n\
    \       [ 4.547124 ,  4.276306 , -3.0559955],\n       [-2.1110737,  2.9072134,\
    \ -6.531638 ],\n       [-1.1700877, -1.672888 ,  9.009623 ]], dtype=float32)),\
    \ ('marker_flow', array([[[[[ 22.430561 ,  24.748943 ],\n          [ 56.649303\
    \ ,  24.132324 ],\n          [ 90.28888  ,  23.011066 ],\n          ...,\n   \
    \       [301.8691   , 235.04755  ],\n          [301.8691   , 235.04755  ],\n \
    \         [301.8691   , 235.04755  ]],\n\n         [[ 26.667873 ,  25.13817  ],\n\
    \          [ 60.034283 ,  22.406149 ],\n          [ 93.96088  ,  21.75981  ],\n\
    \          ...,\n          [304.99097  , 235.77419  ],\n          [304.99097 \
    \ , 235.77419  ],\n          [304.99097  , 235.77419  ]]],\n\n\n        [[[ 73.73886\
    \  ,  11.313962 ],\n          [109.19827  ,  14.963713 ],\n          [145.63916\
    \  ,  18.161497 ],\n          ...,\n          [298.08148  , 236.2939   ],\n  \
    \        [298.08148  , 236.2939   ],\n          [298.08148  , 236.2939   ]],\n\
    \n         [[ 77.41541  ,  10.755278 ],\n          [113.8159   ,  15.370936 ],\n\
    \          [149.6951   ,  18.72521  ],\n          ...,\n          [302.89236 \
    \ , 236.44678  ],\n          [302.89236  , 236.44678  ],\n          [302.89236\
    \  , 236.44678  ]]]],\n\n\n\n       [[[[ 33.57195  ,  37.271767 ],\n         \
    \ [ 69.08759  ,  35.63102  ],\n          [102.7152   ,  35.899586 ],\n       \
    \   ...,\n          [312.59543  , 214.9584   ],\n          [312.59543  , 214.9584\
    \   ],\n          [312.59543  , 214.9584   ]],\n\n         [[ 36.423004 ,  37.901646\
    \ ],\n          [ 72.08851  ,  35.848022 ],\n          [106.57639  ,  34.97205\
    \  ],\n          ...,\n          [315.42352  , 215.27586  ],\n          [315.42352\
    \  , 215.27586  ],\n          [315.42352  , 215.27586  ]]],\n\n\n        [[[ 13.3241205,\
    \  26.288235 ],\n          [ 43.584503 ,  26.099518 ],\n          [ 75.10278 \
    \ ,  23.871878 ],\n          ...,\n          [307.10123  , 239.05159  ],\n   \
    \       [307.10123  , 239.05159  ],\n          [307.10123  , 239.05159  ]],\n\n\
    \         [[ 15.192335 ,  26.663752 ],\n          [ 46.858574 ,  27.070845 ],\n\
    \          [ 79.52777  ,  23.99214  ],\n          ...,\n          [311.43698 \
    \ , 239.19382  ],\n          [311.43698  , 239.19382  ],\n          [311.43698\
    \  , 239.19382  ]]]],\n\n\n\n       [[[[ 12.0519285,  22.587934 ],\n         \
    \ [ 48.834362 ,  24.42665  ],\n          [ 84.96233  ,  27.5819   ],\n       \
    \   ...,\n          [281.53613  , 237.8482   ],\n          [281.53613  , 237.8482\
    \   ],\n          [281.53613  , 237.8482   ]],\n\n         [[ 16.17866  ,  22.023285\
    \ ],\n          [ 52.794502 ,  24.91093  ],\n          [ 86.85446  ,  26.773552\
    \ ],\n          ...,\n          [285.35837  , 237.01727  ],\n          [285.35837\
    \  , 237.01727  ],\n          [285.35837  , 237.01727  ]]],\n\n\n        [[[ 32.58632\
    \  ,  33.256416 ],\n          [ 67.612495 ,  34.565773 ],\n          [102.46786\
    \  ,  36.34399  ],\n          ...,\n          [304.35367  , 231.59767  ],\n  \
    \        [304.35367  , 231.59767  ],\n          [304.35367  , 231.59767  ]],\n\
    \n         [[ 35.730465 ,  33.86192  ],\n          [ 70.73911  ,  33.365784 ],\n\
    \          [105.32158  ,  34.904686 ],\n          ...,\n          [307.51755 \
    \ , 232.51016  ],\n          [307.51755  , 232.51016  ],\n          [307.51755\
    \  , 232.51016  ]]]],\n\n\n\n       [[[[ 18.237963 ,  20.114325 ],\n         \
    \ [ 52.049377 ,  19.682398 ],\n          [ 87.853096 ,  19.89993  ],\n       \
    \   ...,\n          [294.00662  , 205.57373  ],\n          [294.00662  , 205.57373\
    \  ],\n          [294.00662  , 205.57373  ]],\n\n         [[ 21.688454 ,  19.867704\
    \ ],\n          [ 55.351784 ,  18.31938  ],\n          [ 90.11459  ,  19.091385\
    \ ],\n          ...,\n          [297.12082  , 206.91483  ],\n          [297.12082\
    \  , 206.91483  ],\n          [297.12082  , 206.91483  ]]],\n\n\n        [[[ 10.110691\
    \ ,  28.682516 ],\n          [ 43.872276 ,  29.015438 ],\n          [ 78.795265\
    \ ,  27.323612 ],\n          ...,\n          [305.01257  , 219.91841  ],\n   \
    \       [305.01257  , 219.91841  ],\n          [305.01257  , 219.91841  ]],\n\n\
    \         [[ 12.176224 ,  28.781658 ],\n          [ 47.46406  ,  27.75749  ],\n\
    \          [ 81.53892  ,  28.263138 ],\n          ...,\n          [307.98553 \
    \ , 220.59314  ],\n          [307.98553  , 220.59314  ],\n          [307.98553\
    \  , 220.59314  ]]]]], dtype=float32))])"
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''gt_offset'': Box(-3.4028235e+38, 3.4028235e+38, (3,), float32), ''marker_flow'':
    Box(-3.4028235e+38, 3.4028235e+38, (2, 2, 128, 2), float32))'
action_space:
  desc: null
  value: Box(-1.0, 1.0, (3,), float32)
n_envs:
  desc: null
  value: 4
buffer_size:
  desc: null
  value: 200000
batch_size:
  desc: null
  value: 512
learning_starts:
  desc: null
  value: 2000
tau:
  desc: null
  value: 0.005
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: -1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.DictReplayBuffer object at 0x7f71cc91e950>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.DictReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=2, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -3.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.0001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f71cc8ec430>
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FeatureExtractorWithPointNetEncoder(\n \
    \   (feature_extractor_net): PointNetFeatureExtractor(\n      (pointnet_local_fea):\
    \ Sequential(\n        (0): Conv1d(4, 64, kernel_size=(1,), stride=(1,))\n   \
    \     (1): Identity()\n        (2): ReLU()\n        (3): Conv1d(64, 64, kernel_size=(1,),\
    \ stride=(1,))\n        (4): Identity()\n        (5): ReLU()\n      )\n      (pointnet_global_fea):\
    \ PointNetFeaNew(\n        (conv0): Conv1d(64, 64, kernel_size=(1,), stride=(1,))\n\
    \        (bn0): Identity()\n        (conv1): Conv1d(64, 128, kernel_size=(1,),\
    \ stride=(1,))\n        (bn1): Identity()\n        (conv2): Conv1d(128, 512, kernel_size=(1,),\
    \ stride=(1,))\n        (bn2): Identity()\n      )\n      (mlp_output): Sequential(\n\
    \        (0): Linear(in_features=512, out_features=256, bias=True)\n        (1):\
    \ ReLU()\n        (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \        (3): ReLU()\n        (4): Linear(in_features=256, out_features=32, bias=True)\n\
    \      )\n    )\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=64,\
    \ out_features=256, bias=True)\n    (1): Identity()\n    (2): ReLU()\n    (3):\
    \ Linear(in_features=256, out_features=256, bias=True)\n    (4): Identity()\n\
    \    (5): ReLU()\n    (6): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (7): Tanh()\n  )\n  (mu): Linear(in_features=256, out_features=3, bias=True)\n\
    \  (log_std): Linear(in_features=256, out_features=3, bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CriticFeatureExtractor()\n  (qf0):\
    \ Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n \
    \   (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n  (qf1): Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n\
    \    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CriticFeatureExtractor()\n  (qf0):\
    \ Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n \
    \   (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n  (qf1): Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n\
    \    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f733b827910>
