wandb_version: 1

env:
  desc: null
  value:
    step_penalty: 1
    final_reward: 10
    max_action:
    - 2.0
    - 2.0
    - 4.0
    max_steps: 100
    z_step_size: 0.125
    peg_hole_path_file: configs/peg_insertion/3shape_2.0mm.txt
    peg_x_max_offset: 5.0
    peg_y_max_offset: 5.0
    peg_theta_max_offset: 10.0
    marker_interval_range:
    - 1.95
    - 2.15
    marker_rotation_range: 0.1
    marker_translation_range:
    - 1
    - 1
    marker_pos_shift_range:
    - 0.1
    - 0.1
    marker_random_noise: 0.5
    marker_lose_tracking_probability: 0.01
    normalize: false
policy:
  desc: null
  value:
    buffer_size: 200000
    train_freq: 2
    gradient_steps: -1
    learning_starts: 2000
    action_noise: VecNoise(BaseNoise=NormalActionNoise(mu=[0 0 0], sigma=[0.5 0.5
      0.5])), n_envs=8)
    batch_size: 256
    learning_rate: 0.0001
    optimize_memory_usage: false
    ent_coef: auto
    target_update_interval: 1
    target_entropy: auto
    use_sde: false
    sde_sample_freq: -1
    use_sde_at_warmup: false
    policy_kwargs:
      pointnet_in_dim: 4
      pointnet_out_dim: 32
      pointnet_batchnorm: false
      pointnet_layernorm: true
      zero_init_output: true
      use_sde: false
    device: cuda:0
    seed: 0
    tensorboard_log: /media/lab/data/yzk/ManiSkill-ViTac2024/scripts/../training_log/3shape_2.0mm_2024-03-17_20-12-23.193
train:
  desc: null
  value:
    total_timesteps: 500000
    log_interval: 10
    checkpoint_every: 2000
    eval_freq: 2000
    n_eval: 50
    parallel: 8
    seed: 0
    device: cuda:0
    gpu: 0
    name: 3shape_2.0mm
    wandb_name: ManiSkill_ViTac
    emp: {}
cfg:
  desc: null
  value: configs/parameters/peg_insertion_sac.yaml
no_render:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/scripts/train_sac.py
    python_version: 3.10.0
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710677548.715749
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.10.0
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'solutions.policies_sac.SACPolicyForPointFlowEnv'>
device:
  desc: null
  value: cuda:0
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''pointnet_in_dim'': 4, ''pointnet_out_dim'': 32, ''pointnet_batchnorm'':
    False, ''pointnet_layernorm'': True, ''zero_init_output'': True, ''use_sde'':
    False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 500000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: 0
action_noise:
  desc: null
  value: VecNoise(BaseNoise=NormalActionNoise(mu=[0 0 0], sigma=[0.5 0.5 0.5])), n_envs=8)
start_time:
  desc: null
  value: 1710677553434157785
learning_rate:
  desc: null
  value: 0.0001
tensorboard_log:
  desc: null
  value: /media/lab/data/yzk/ManiSkill-ViTac2024/scripts/../training_log/3shape_2.0mm_2024-03-17_20-12-23.193
_last_obs:
  desc: null
  value: "OrderedDict([('gt_offset', array([[ 3.5005581 ,  4.553451  , -6.818689 \
    \ ],\n       [-3.369071  , -2.1854327 ,  3.1483107 ],\n       [-3.8569636 , -1.7015973\
    \ , -5.5092287 ],\n       [-2.7053723 ,  2.1661892 ,  9.014434  ],\n       [ 4.40699\
    \   , -1.7885414 ,  6.620373  ],\n       [-0.36294368,  4.832942  , -9.315404\
    \  ],\n       [-3.8947232 , -2.3278909 ,  1.0255351 ],\n       [-2.9267771 , \
    \ 4.23324   ,  9.139025  ]], dtype=float32)), ('marker_flow', array([[[[[ 14.130702\
    \ ,  33.394623 ],\n          [ 45.631542 ,  31.613153 ],\n          [ 77.691956\
    \ ,  29.257593 ],\n          ...,\n          [306.60995  , 232.37852  ],\n   \
    \       [306.60995  , 232.37852  ],\n          [306.60995  , 232.37852  ]],\n\n\
    \         [[ 17.092506 ,  33.200317 ],\n          [ 49.763992 ,  31.871866 ],\n\
    \          [ 81.26345  ,  28.171225 ],\n          ...,\n          [309.16995 \
    \ , 233.06525  ],\n          [309.16995  , 233.06525  ],\n          [309.16995\
    \  , 233.06525  ]]],\n\n\n        [[[294.49762  ,  15.784494 ],\n          [ 26.533543\
    \ ,  28.358675 ],\n          [ 60.27586  ,  31.149302 ],\n          ...,\n   \
    \       [308.4419   , 234.1779   ],\n          [308.4419   , 234.1779   ],\n \
    \         [308.4419   , 234.1779   ]],\n\n         [[297.20157  ,  16.011126 ],\n\
    \          [ 29.248747 ,  27.912363 ],\n          [ 63.59069  ,  31.2741   ],\n\
    \          ...,\n          [312.43295  , 234.01613  ],\n          [312.43295 \
    \ , 234.01613  ],\n          [312.43295  , 234.01613  ]]]],\n\n\n\n       [[[[\
    \ 31.59527  ,  40.33744  ],\n          [ 67.349236 ,  40.36562  ],\n         \
    \ [101.25809  ,  36.41627  ],\n          ...,\n          [302.4028   , 230.82246\
    \  ],\n          [302.4028   , 230.82246  ],\n          [302.4028   , 230.82246\
    \  ]],\n\n         [[ 34.623894 ,  40.740696 ],\n          [ 70.7923   ,  39.93616\
    \  ],\n          [103.85036  ,  37.778557 ],\n          ...,\n          [305.47855\
    \  , 230.4649   ],\n          [305.47855  , 230.4649   ],\n          [305.47855\
    \  , 230.4649   ]]],\n\n\n        [[[ 26.916105 ,  27.651049 ],\n          [ 60.361084\
    \ ,  31.743986 ],\n          [ 95.28095  ,  31.074408 ],\n          ...,\n   \
    \       [292.08136  , 236.3161   ],\n          [292.08136  , 236.3161   ],\n \
    \         [292.08136  , 236.3161   ]],\n\n         [[ 30.062359 ,  27.598969 ],\n\
    \          [ 63.0098   ,  30.661327 ],\n          [ 98.2894   ,  30.21261  ],\n\
    \          ...,\n          [294.53882  , 236.36119  ],\n          [294.53882 \
    \ , 236.36119  ],\n          [294.53882  , 236.36119  ]]]],\n\n\n\n       [[[[\
    \ 13.723097 ,  36.520657 ],\n          [ 47.619293 ,  34.642426 ],\n         \
    \ [ 79.61965  ,  37.18709  ],\n          ...,\n          [285.4925   , 234.42819\
    \  ],\n          [285.4925   , 234.42819  ],\n          [285.4925   , 234.42819\
    \  ]],\n\n         [[ 16.59272  ,  36.851322 ],\n          [ 49.881336 ,  34.52035\
    \  ],\n          [ 82.50061  ,  37.559048 ],\n          ...,\n          [289.03375\
    \  , 234.81082  ],\n          [289.03375  , 234.81082  ],\n          [289.03375\
    \  , 234.81082  ]]],\n\n\n        [[[ 13.5199175,  14.631241 ],\n          [ 44.377777\
    \ ,  10.39937  ],\n          [ 78.54693  ,   9.17096  ],\n          ...,\n   \
    \       [317.4866   , 210.40761  ],\n          [317.4866   , 210.40761  ],\n \
    \         [317.4866   , 210.40761  ]],\n\n         [[ 17.102356 ,  13.671322 ],\n\
    \          [ 47.85464  ,  10.67651  ],\n          [ 82.02895  ,   9.978085 ],\n\
    \          ...,\n          [321.3557   , 210.03154  ],\n          [321.3557  \
    \ , 210.03154  ],\n          [321.3557   , 210.03154  ]]]],\n\n\n\n       ...,\n\
    \n\n\n       [[[[ 18.867651 ,  13.31995  ],\n          [ 50.844746 ,  12.924794\
    \ ],\n          [ 80.90987  ,  12.760828 ],\n          ...,\n          [282.00272\
    \  , 232.06192  ],\n          [282.00272  , 232.06192  ],\n          [282.00272\
    \  , 232.06192  ]],\n\n         [[ 21.577803 ,  13.259024 ],\n          [ 54.431435\
    \ ,  13.222319 ],\n          [ 85.77016  ,  13.304918 ],\n          ...,\n   \
    \       [285.01147  , 232.46085  ],\n          [285.01147  , 232.46085  ],\n \
    \         [285.01147  , 232.46085  ]]],\n\n\n        [[[ 11.25096  ,  24.21393\
    \  ],\n          [ 45.456    ,  22.46307  ],\n          [ 76.59474  ,  20.011282\
    \ ],\n          ...,\n          [286.07196  , 220.56602  ],\n          [286.07196\
    \  , 220.56602  ],\n          [286.07196  , 220.56602  ]],\n\n         [[ 14.6631975,\
    \  24.566376 ],\n          [ 49.145267 ,  21.14995  ],\n          [ 79.425934\
    \ ,  20.130089 ],\n          ...,\n          [288.22186  , 221.40771  ],\n   \
    \       [288.22186  , 221.40771  ],\n          [288.22186  , 221.40771  ]]]],\n\
    \n\n\n       [[[[ 33.16554  ,  21.231806 ],\n          [ 68.87131  ,  19.355042\
    \ ],\n          [ 98.88791  ,  17.877285 ],\n          ...,\n          [303.7546\
    \   , 224.87503  ],\n          [303.7546   , 224.87503  ],\n          [303.7546\
    \   , 224.87503  ]],\n\n         [[ 34.773483 ,  19.501785 ],\n          [ 71.54066\
    \  ,  20.639603 ],\n          [103.06555  ,  16.490068 ],\n          ...,\n  \
    \        [307.10336  , 225.48297  ],\n          [307.10336  , 225.48297  ],\n\
    \          [307.10336  , 225.48297  ]]],\n\n\n        [[[ 16.331186 ,  30.154556\
    \ ],\n          [ 48.419106 ,  30.365404 ],\n          [ 80.73796  ,  27.238138\
    \ ],\n          ...,\n          [314.21866  , 233.42542  ],\n          [314.21866\
    \  , 233.42542  ],\n          [314.21866  , 233.42542  ]],\n\n         [[ 20.000507\
    \ ,  29.753065 ],\n          [ 52.08171  ,  30.642199 ],\n          [ 83.65999\
    \  ,  26.983404 ],\n          ...,\n          [315.30994  , 232.4654   ],\n  \
    \        [315.30994  , 232.4654   ],\n          [315.30994  , 232.4654   ]]]],\n\
    \n\n\n       [[[[ 14.925707 ,  18.853275 ],\n          [ 49.536766 ,  19.17705\
    \  ],\n          [ 81.98458  ,  19.877794 ],\n          ...,\n          [281.14114\
    \  , 218.29659  ],\n          [281.14114  , 218.29659  ],\n          [281.14114\
    \  , 218.29659  ]],\n\n         [[ 17.921486 ,  19.454496 ],\n          [ 52.811493\
    \ ,  19.926168 ],\n          [ 85.23912  ,  19.697515 ],\n          ...,\n   \
    \       [285.13083  , 217.64725  ],\n          [285.13083  , 217.64725  ],\n \
    \         [285.13083  , 217.64725  ]]],\n\n\n        [[[ 31.03052  ,  22.301973\
    \ ],\n          [ 65.976776 ,  22.61915  ],\n          [ 95.41654  ,  23.587357\
    \ ],\n          ...,\n          [279.27304  , 237.94489  ],\n          [279.27304\
    \  , 237.94489  ],\n          [279.27304  , 237.94489  ]],\n\n         [[ 35.988815\
    \ ,  21.523972 ],\n          [ 69.08193  ,  21.510818 ],\n          [ 99.134575\
    \ ,  23.315294 ],\n          ...,\n          [282.48163  , 239.24017  ],\n   \
    \       [282.48163  , 239.24017  ],\n          [282.48163  , 239.24017  ]]]]],\
    \ dtype=float32))])"
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True  True  True  True  True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''gt_offset'': Box(-3.4028235e+38, 3.4028235e+38, (3,), float32), ''marker_flow'':
    Box(-3.4028235e+38, 3.4028235e+38, (2, 2, 128, 2), float32))'
action_space:
  desc: null
  value: Box(-1.0, 1.0, (3,), float32)
n_envs:
  desc: null
  value: 8
buffer_size:
  desc: null
  value: 200000
batch_size:
  desc: null
  value: 256
learning_starts:
  desc: null
  value: 2000
tau:
  desc: null
  value: 0.005
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: -1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.DictReplayBuffer object at 0x7fba08f9ff70>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.DictReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=2, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -3.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.0001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fba08fb9ab0>
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FeatureExtractorWithPointNetEncoder(\n \
    \   (feature_extractor_net): PointNetFeatureExtractor(\n      (pointnet_local_fea):\
    \ Sequential(\n        (0): Conv1d(4, 64, kernel_size=(1,), stride=(1,))\n   \
    \     (1): Identity()\n        (2): ReLU()\n        (3): Conv1d(64, 64, kernel_size=(1,),\
    \ stride=(1,))\n        (4): Identity()\n        (5): ReLU()\n      )\n      (pointnet_global_fea):\
    \ PointNetFeaNew(\n        (conv0): Conv1d(64, 64, kernel_size=(1,), stride=(1,))\n\
    \        (bn0): Identity()\n        (conv1): Conv1d(64, 128, kernel_size=(1,),\
    \ stride=(1,))\n        (bn1): Identity()\n        (conv2): Conv1d(128, 512, kernel_size=(1,),\
    \ stride=(1,))\n        (bn2): Identity()\n      )\n      (mlp_output): Sequential(\n\
    \        (0): Linear(in_features=512, out_features=256, bias=True)\n        (1):\
    \ ReLU()\n        (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \        (3): ReLU()\n        (4): Linear(in_features=256, out_features=32, bias=True)\n\
    \      )\n    )\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=64,\
    \ out_features=256, bias=True)\n    (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)\n\
    \    (2): ReLU()\n    (3): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)\n    (5): ReLU()\n\
    \    (6): Linear(in_features=256, out_features=256, bias=True)\n    (7): Tanh()\n\
    \  )\n  (mu): Linear(in_features=256, out_features=3, bias=True)\n  (log_std):\
    \ Linear(in_features=256, out_features=3, bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CriticFeatureExtractor()\n  (qf0):\
    \ Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n \
    \   (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n  (qf1): Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n\
    \    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CriticFeatureExtractor()\n  (qf0):\
    \ Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n \
    \   (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n  (qf1): Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n\
    \    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7fba4eedde70>
