wandb_version: 1

env:
  desc: null
  value:
    step_penalty: 1
    final_reward: 10
    max_action:
    - 2.0
    - 2.0
    - 4.0
    max_steps: 8
    z_step_size: 0.125
    peg_hole_path_file: configs/peg_insertion/3shape_1.5mm.txt
    peg_x_max_offset: 5.0
    peg_y_max_offset: 5.0
    peg_theta_max_offset: 10.0
    marker_interval_range:
    - 1.95
    - 2.15
    marker_rotation_range: 0.1
    marker_translation_range:
    - 1
    - 1
    marker_pos_shift_range:
    - 0.1
    - 0.1
    marker_random_noise: 0.5
    marker_lose_tracking_probability: 0.01
    normalize: false
policy:
  desc: null
  value:
    buffer_size: 200000
    train_freq: 2
    gradient_steps: -1
    learning_starts: 2000
    action_noise: VecNoise(BaseNoise=NormalActionNoise(mu=[0 0 0], sigma=[0.5 0.5
      0.5])), n_envs=4)
    batch_size: 512
    learning_rate: 0.0001
    optimize_memory_usage: false
    ent_coef: auto
    target_update_interval: 1
    target_entropy: auto
    use_sde: false
    sde_sample_freq: -1
    use_sde_at_warmup: false
    policy_kwargs:
      pointnet_in_dim: 4
      pointnet_out_dim: 32
      pointnet_batchnorm: false
      pointnet_layernorm: true
      zero_init_output: true
      use_sde: false
    device: cuda:0
    seed: 0
    tensorboard_log: /home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../training_log/3shape_1.5mm_batch_size_512_lr_0.0001_2024-03-21_19-49-24.152
train:
  desc: null
  value:
    total_timesteps: 500000
    log_interval: 6
    checkpoint_every: 2000
    eval_freq: 2000
    n_eval: 50
    parallel: 4
    seed: 0
    device: cuda:0
    gpu: 0
    name: 3shape_1.5mm_batch_size_512_lr_0.0001
    wandb_name: ManiSkill_ViTac
    emp: {}
cfg:
  desc: null
  value: configs/parameters/peg_insertion_sac.yaml
no_render:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/scripts/train_sac.py
    python_version: 3.10.0
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711021769.976079
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.10.0
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'solutions.policies_sac.SACPolicyForPointFlowEnv'>
device:
  desc: null
  value: cuda:0
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''pointnet_in_dim'': 4, ''pointnet_out_dim'': 32, ''pointnet_batchnorm'':
    False, ''pointnet_layernorm'': True, ''zero_init_output'': True, ''use_sde'':
    False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 500000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: 0
action_noise:
  desc: null
  value: VecNoise(BaseNoise=NormalActionNoise(mu=[0 0 0], sigma=[0.5 0.5 0.5])), n_envs=4)
start_time:
  desc: null
  value: 1711021771581585150
learning_rate:
  desc: null
  value: 0.0001
tensorboard_log:
  desc: null
  value: /home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../training_log/3shape_1.5mm_batch_size_512_lr_0.0001_2024-03-21_19-49-24.152
_last_obs:
  desc: null
  value: "OrderedDict([('gt_offset', array([[ 2.2938802 , -4.4943037 ,  3.1189811\
    \ ],\n       [-2.1202617 , -2.3218715 , -3.9426196 ],\n       [-4.460222  ,  2.3152611\
    \ , -7.8929434 ],\n       [-3.0639708 ,  0.17811728,  8.410518  ]], dtype=float32)),\
    \ ('marker_flow', array([[[[[ 32.16046  ,  35.176533 ],\n          [ 64.72465\
    \  ,  35.650883 ],\n          [ 98.21432  ,  37.024216 ],\n          ...,\n  \
    \        [263.12073  , 239.14171  ],\n          [263.12073  , 239.14171  ],\n\
    \          [263.12073  , 239.14171  ]],\n\n         [[ 34.529896 ,  35.159267\
    \ ],\n          [ 67.380066 ,  36.711704 ],\n          [102.00276  ,  37.39361\
    \  ],\n          ...,\n          [268.56644  , 237.76315  ],\n          [268.56644\
    \  , 237.76315  ],\n          [268.56644  , 237.76315  ]]],\n\n\n        [[[ \
    \ 8.426226 ,  29.290194 ],\n          [ 42.312775 ,  30.727467 ],\n          [\
    \ 71.63796  ,  29.383474 ],\n          ...,\n          [300.22134  , 207.13823\
    \  ],\n          [300.22134  , 207.13823  ],\n          [300.22134  , 207.13823\
    \  ]],\n\n         [[ 11.49129  ,  28.972198 ],\n          [ 44.673717 ,  30.590864\
    \ ],\n          [ 76.52873  ,  30.531649 ],\n          ...,\n          [304.07397\
    \  , 206.96149  ],\n          [304.07397  , 206.96149  ],\n          [304.07397\
    \  , 206.96149  ]]]],\n\n\n\n       [[[[ 15.916398 ,  26.32772  ],\n         \
    \ [ 47.01877  ,  25.413843 ],\n          [ 81.05315  ,  24.73678  ],\n       \
    \   ...,\n          [308.79456  , 228.32677  ],\n          [308.79456  , 228.32677\
    \  ],\n          [308.79456  , 228.32677  ]],\n\n         [[ 21.306372 ,  26.961298\
    \ ],\n          [ 51.011723 ,  26.238573 ],\n          [ 84.0533   ,  24.031027\
    \ ],\n          ...,\n          [311.1757   , 228.15273  ],\n          [311.1757\
    \   , 228.15273  ],\n          [311.1757   , 228.15273  ]]],\n\n\n        [[[\
    \ 23.618738 ,  27.673079 ],\n          [ 59.42725  ,  24.752892 ],\n         \
    \ [ 93.500435 ,  21.867678 ],\n          ...,\n          [289.3137   , 237.65912\
    \  ],\n          [289.3137   , 237.65912  ],\n          [289.3137   , 237.65912\
    \  ]],\n\n         [[ 27.451887 ,  27.399395 ],\n          [ 61.529312 ,  24.495033\
    \ ],\n          [ 97.209564 ,  21.97794  ],\n          ...,\n          [293.92325\
    \  , 238.26558  ],\n          [293.92325  , 238.26558  ],\n          [293.92325\
    \  , 238.26558  ]]]],\n\n\n\n       [[[[ 25.264782 ,  21.790607 ],\n         \
    \ [ 59.028473 ,  19.72151  ],\n          [ 92.50741  ,  19.825493 ],\n       \
    \   ...,\n          [297.21487  , 214.18413  ],\n          [297.21487  , 214.18413\
    \  ],\n          [297.21487  , 214.18413  ]],\n\n         [[ 26.311625 ,  20.215603\
    \ ],\n          [ 61.997166 ,  20.001217 ],\n          [ 95.99235  ,  19.402895\
    \ ],\n          ...,\n          [300.38098  , 215.25064  ],\n          [300.38098\
    \  , 215.25064  ],\n          [300.38098  , 215.25064  ]]],\n\n\n        [[[ \
    \ 8.075491 ,  42.0856   ],\n          [ 41.196518 ,  40.93258  ],\n          [\
    \ 76.71883  ,  40.905727 ],\n          ...,\n          [284.92307  , 224.45094\
    \  ],\n          [284.92307  , 224.45094  ],\n          [284.92307  , 224.45094\
    \  ]],\n\n         [[ 10.372277 ,  42.375607 ],\n          [ 45.847614 ,  41.158234\
    \ ],\n          [ 78.89222  ,  40.56739  ],\n          ...,\n          [288.715\
    \    , 224.7238   ],\n          [288.715    , 224.7238   ],\n          [288.715\
    \    , 224.7238   ]]]],\n\n\n\n       [[[[ 22.45641  ,  27.03476  ],\n       \
    \   [ 56.4807   ,  24.500425 ],\n          [ 92.20207  ,  21.667145 ],\n     \
    \     ...,\n          [283.0096   , 231.0032   ],\n          [283.0096   , 231.0032\
    \   ],\n          [283.0096   , 231.0032   ]],\n\n         [[ 26.78351  ,  25.68721\
    \  ],\n          [ 60.213966 ,  24.36884  ],\n          [ 95.66632  ,  20.407284\
    \ ],\n          ...,\n          [285.49026  , 231.82886  ],\n          [285.49026\
    \  , 231.82886  ],\n          [285.49026  , 231.82886  ]]],\n\n\n        [[[ \
    \ 6.9198008,  15.892034 ],\n          [ 73.216515 ,  18.012356 ],\n          [104.68652\
    \  ,  16.837017 ],\n          ...,\n          [ 96.47162  , 236.4423   ],\n  \
    \        [ 96.47162  , 236.4423   ],\n          [ 96.47162  , 236.4423   ]],\n\
    \n         [[  8.877122 ,  16.126942 ],\n          [ 76.83697  ,  19.159271 ],\n\
    \          [107.05367  ,  16.773533 ],\n          ...,\n          [ 99.94993 \
    \ , 237.3631   ],\n          [ 99.94993  , 237.3631   ],\n          [ 99.94993\
    \  , 237.3631   ]]]]], dtype=float32))])"
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''gt_offset'': Box(-3.4028235e+38, 3.4028235e+38, (3,), float32), ''marker_flow'':
    Box(-3.4028235e+38, 3.4028235e+38, (2, 2, 128, 2), float32))'
action_space:
  desc: null
  value: Box(-1.0, 1.0, (3,), float32)
n_envs:
  desc: null
  value: 4
buffer_size:
  desc: null
  value: 200000
batch_size:
  desc: null
  value: 512
learning_starts:
  desc: null
  value: 2000
tau:
  desc: null
  value: 0.005
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: -1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.DictReplayBuffer object at 0x7fd57832f8b0>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.DictReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=2, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -3.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.0001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fd578339ea0>
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FeatureExtractorWithPointNetEncoder(\n \
    \   (feature_extractor_net): PointNetFeatureExtractor(\n      (pointnet_local_fea):\
    \ Sequential(\n        (0): Conv1d(4, 64, kernel_size=(1,), stride=(1,))\n   \
    \     (1): Identity()\n        (2): ReLU()\n        (3): Conv1d(64, 64, kernel_size=(1,),\
    \ stride=(1,))\n        (4): Identity()\n        (5): ReLU()\n      )\n      (pointnet_global_fea):\
    \ PointNetFeaNew(\n        (conv0): Conv1d(64, 64, kernel_size=(1,), stride=(1,))\n\
    \        (bn0): Identity()\n        (conv1): Conv1d(64, 128, kernel_size=(1,),\
    \ stride=(1,))\n        (bn1): Identity()\n        (conv2): Conv1d(128, 512, kernel_size=(1,),\
    \ stride=(1,))\n        (bn2): Identity()\n      )\n      (mlp_output): Sequential(\n\
    \        (0): Linear(in_features=512, out_features=256, bias=True)\n        (1):\
    \ ReLU()\n        (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \        (3): ReLU()\n        (4): Linear(in_features=256, out_features=32, bias=True)\n\
    \      )\n    )\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=64,\
    \ out_features=256, bias=True)\n    (1): Identity()\n    (2): ReLU()\n    (3):\
    \ Linear(in_features=256, out_features=256, bias=True)\n    (4): Identity()\n\
    \    (5): ReLU()\n    (6): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (7): Tanh()\n  )\n  (mu): Linear(in_features=256, out_features=3, bias=True)\n\
    \  (log_std): Linear(in_features=256, out_features=3, bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CriticFeatureExtractor()\n  (qf0):\
    \ Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n \
    \   (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n  (qf1): Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n\
    \    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CriticFeatureExtractor()\n  (qf0):\
    \ Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n \
    \   (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n  (qf1): Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n\
    \    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7fd5d1a49540>
