wandb_version: 1

env:
  desc: null
  value:
    step_penalty: 1
    final_reward: 10
    max_action:
    - 2.0
    - 2.0
    - 4.0
    max_steps: 8
    z_step_size: 0.125
    peg_hole_path_file: configs/peg_insertion/3shape_1.0mm.txt
    peg_x_max_offset: 5.0
    peg_y_max_offset: 5.0
    peg_theta_max_offset: 10.0
    marker_interval_range:
    - 1.95
    - 2.15
    marker_rotation_range: 0.1
    marker_translation_range:
    - 1
    - 1
    marker_pos_shift_range:
    - 0.1
    - 0.1
    marker_random_noise: 0.5
    marker_lose_tracking_probability: 0.01
    normalize: false
policy:
  desc: null
  value:
    buffer_size: 200000
    train_freq: 2
    gradient_steps: -1
    learning_starts: 32
    action_noise: VecNoise(BaseNoise=NormalActionNoise(mu=[0 0 0], sigma=[0.5 0.5
      0.5])), n_envs=4)
    batch_size: 64
    learning_rate: 0.0003
    optimize_memory_usage: false
    ent_coef: auto
    target_update_interval: 1
    target_entropy: auto
    use_sde: false
    sde_sample_freq: -1
    use_sde_at_warmup: false
    policy_kwargs:
      pointnet_in_dim: 4
      pointnet_out_dim: 32
      pointnet_batchnorm: false
      pointnet_layernorm: true
      zero_init_output: true
      use_sde: false
    device: cuda:0
    seed: 0
    tensorboard_log: /home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../training_log/7shape_1.5mm_2024-03-10_02-28-05.841
train:
  desc: null
  value:
    total_timesteps: 500000
    log_interval: 10
    checkpoint_every: 2000
    eval_freq: 2000
    n_eval: 50
    parallel: 4
    seed: 0
    device: cuda:0
    gpu: 0
    name: 7shape_1.5mm
    wandb_name: ManiSkill_ViTac
    emp: {}
cfg:
  desc: null
  value: configs/parameters/peg_insertion_sac.yaml
no_render:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/scripts/train_sac.py
    python_version: 3.10.0
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710008957.03231
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.10.0
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'solutions.policies_sac.SACPolicyForPointFlowEnv'>
device:
  desc: null
  value: cuda:0
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''pointnet_in_dim'': 4, ''pointnet_out_dim'': 32, ''pointnet_batchnorm'':
    False, ''pointnet_layernorm'': True, ''zero_init_output'': True, ''use_sde'':
    False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 500000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: 0
action_noise:
  desc: null
  value: VecNoise(BaseNoise=NormalActionNoise(mu=[0 0 0], sigma=[0.5 0.5 0.5])), n_envs=4)
start_time:
  desc: null
  value: 1710008967848045588
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: /home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../training_log/7shape_1.5mm_2024-03-10_02-28-05.841
_last_obs:
  desc: null
  value: "OrderedDict([('gt_offset', array([[-2.3728538 ,  4.491601  ,  7.2462373\
    \ ],\n       [ 1.2080413 , -3.4470875 , -2.814112  ],\n       [-0.01742603, -2.7304876\
    \ , -5.6096344 ],\n       [-3.4039764 , -3.813636  ,  7.611666  ]], dtype=float32)),\
    \ ('marker_flow', array([[[[[  9.669184,  33.494247],\n          [ 44.492256,\
    \  33.736763],\n          [ 78.038155,  34.83177 ],\n          ...,\n        \
    \  [298.3029  , 230.2636  ],\n          [298.3029  , 230.2636  ],\n          [298.3029\
    \  , 230.2636  ]],\n\n         [[ 13.017457,  34.04751 ],\n          [ 46.773247,\
    \  33.624924],\n          [ 81.81777 ,  35.85132 ],\n          ...,\n        \
    \  [301.30594 , 229.85576 ],\n          [301.30594 , 229.85576 ],\n          [301.30594\
    \ , 229.85576 ]]],\n\n\n        [[[  8.591345,  19.740711],\n          [ 38.28331\
    \ ,  20.371183],\n          [ 72.148674,  15.910681],\n          ...,\n      \
    \    [283.5713  , 215.8707  ],\n          [283.5713  , 215.8707  ],\n        \
    \  [283.5713  , 215.8707  ]],\n\n         [[ 10.76419 ,  20.316378],\n       \
    \   [ 40.135464,  19.043596],\n          [ 75.23291 ,  16.284506],\n         \
    \ ...,\n          [287.02673 , 216.12405 ],\n          [287.02673 , 216.12405\
    \ ],\n          [287.02673 , 216.12405 ]]]],\n\n\n\n       [[[[  8.419262,  21.353144],\n\
    \          [ 42.709057,  22.779432],\n          [ 77.70361 ,  23.300161],\n  \
    \        ...,\n          [302.7971  , 224.77756 ],\n          [302.7971  , 224.77756\
    \ ],\n          [302.7971  , 224.77756 ]],\n\n         [[ 11.71495 ,  21.327333],\n\
    \          [ 45.931416,  22.909678],\n          [ 79.30498 ,  23.925743],\n  \
    \        ...,\n          [304.25095 , 224.46144 ],\n          [304.25095 , 224.46144\
    \ ],\n          [304.25095 , 224.46144 ]]],\n\n\n        [[[ 25.441236,  29.21932\
    \ ],\n          [ 59.49643 ,  31.929522],\n          [ 94.07566 ,  32.741318],\n\
    \          ...,\n          [290.33908 , 228.4897  ],\n          [290.33908 , 228.4897\
    \  ],\n          [290.33908 , 228.4897  ]],\n\n         [[ 28.45102 ,  29.552801],\n\
    \          [ 63.722622,  31.76548 ],\n          [ 98.20232 ,  32.96862 ],\n  \
    \        ...,\n          [293.15265 , 228.67026 ],\n          [293.15265 , 228.67026\
    \ ],\n          [293.15265 , 228.67026 ]]]],\n\n\n\n       [[[[ 21.481894,  43.223946],\n\
    \          [ 57.17615 ,  41.281624],\n          [ 89.96845 ,  42.641613],\n  \
    \        ...,\n          [297.46115 , 236.8837  ],\n          [297.46115 , 236.8837\
    \  ],\n          [297.46115 , 236.8837  ]],\n\n         [[ 24.616451,  42.02219\
    \ ],\n          [ 60.74252 ,  40.869152],\n          [ 93.14099 ,  42.121292],\n\
    \          ...,\n          [302.3068  , 238.63705 ],\n          [302.3068  , 238.63705\
    \ ],\n          [302.3068  , 238.63705 ]]],\n\n\n        [[[112.71406 ,  11.170289],\n\
    \          [182.00545 ,  13.908776],\n          [218.29147 ,  13.353241],\n  \
    \        ...,\n          [283.42493 , 213.57693 ],\n          [283.42493 , 213.57693\
    \ ],\n          [283.42493 , 213.57693 ]],\n\n         [[116.04943 ,  10.259037],\n\
    \          [184.30283 ,  12.942764],\n          [223.13959 ,  13.619348],\n  \
    \        ...,\n          [286.23688 , 213.27966 ],\n          [286.23688 , 213.27966\
    \ ],\n          [286.23688 , 213.27966 ]]]],\n\n\n\n       [[[[ 14.337858,  14.930899],\n\
    \          [ 50.06877 ,  17.299248],\n          [ 84.53694 ,  20.833385],\n  \
    \        ...,\n          [302.91177 , 233.77434 ],\n          [302.91177 , 233.77434\
    \ ],\n          [302.91177 , 233.77434 ]],\n\n         [[ 18.203026,  14.315481],\n\
    \          [ 52.509686,  17.647112],\n          [ 87.72129 ,  20.013643],\n  \
    \        ...,\n          [306.1366  , 233.82304 ],\n          [306.1366  , 233.82304\
    \ ],\n          [306.1366  , 233.82304 ]]],\n\n\n        [[[ 11.512327,  31.27203\
    \ ],\n          [ 46.006264,  30.539923],\n          [ 81.19753 ,  29.386099],\n\
    \          ...,\n          [295.4468  , 216.3907  ],\n          [295.4468  , 216.3907\
    \  ],\n          [295.4468  , 216.3907  ]],\n\n         [[ 14.126054,  30.363987],\n\
    \          [ 49.75004 ,  32.101345],\n          [ 83.22357 ,  29.074223],\n  \
    \        ...,\n          [299.0946  , 217.37456 ],\n          [299.0946  , 217.37456\
    \ ],\n          [299.0946  , 217.37456 ]]]]], dtype=float32))])"
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''gt_offset'': Box(-3.4028235e+38, 3.4028235e+38, (3,), float32), ''marker_flow'':
    Box(-3.4028235e+38, 3.4028235e+38, (2, 2, 128, 2), float32))'
action_space:
  desc: null
  value: Box(-1.0, 1.0, (3,), float32)
n_envs:
  desc: null
  value: 4
buffer_size:
  desc: null
  value: 200000
batch_size:
  desc: null
  value: 64
learning_starts:
  desc: null
  value: 32
tau:
  desc: null
  value: 0.005
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: -1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.DictReplayBuffer object at 0x7f3716835c00>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.DictReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=2, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -3.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.0003\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f3727d0eb90>
actor:
  desc: null
  value: "CustomActor(\n  (features_extractor): FeatureExtractorWithPointNetEncoder(\n\
    \    (feature_extractor_net): PointNetFeatureExtractor(\n      (pointnet_local_fea):\
    \ Sequential(\n        (0): Conv1d(4, 64, kernel_size=(1,), stride=(1,))\n   \
    \     (1): Identity()\n        (2): ReLU()\n        (3): Conv1d(64, 64, kernel_size=(1,),\
    \ stride=(1,))\n        (4): Identity()\n        (5): ReLU()\n      )\n      (pointnet_global_fea):\
    \ PointNetFeaNew(\n        (conv0): Conv1d(64, 64, kernel_size=(1,), stride=(1,))\n\
    \        (bn0): Identity()\n        (conv1): Conv1d(64, 128, kernel_size=(1,),\
    \ stride=(1,))\n        (bn1): Identity()\n        (conv2): Conv1d(128, 512, kernel_size=(1,),\
    \ stride=(1,))\n        (bn2): Identity()\n      )\n      (mlp_output): Sequential(\n\
    \        (0): Linear(in_features=512, out_features=256, bias=True)\n        (1):\
    \ ReLU()\n        (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \        (3): ReLU()\n        (4): Linear(in_features=256, out_features=32, bias=True)\n\
    \      )\n    )\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=64,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n  )\n  (mu): Linear(in_features=256,\
    \ out_features=3, bias=True)\n  (log_std): Linear(in_features=256, out_features=3,\
    \ bias=True)\n  (mlp_policy): Sequential(\n    (0): Linear(in_features=64, out_features=256,\
    \ bias=True)\n    (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)\n\
    \    (2): ReLU()\n    (3): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)\n    (5): ReLU()\n\
    \    (6): Linear(in_features=256, out_features=3, bias=True)\n    (7): Tanh()\n\
    \  )\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CriticFeatureExtractor()\n  (qf0):\
    \ Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n \
    \   (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n  (qf1): Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n\
    \    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CriticFeatureExtractor()\n  (qf0):\
    \ Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n \
    \   (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n  (qf1): Sequential(\n    (0): Linear(in_features=6, out_features=256, bias=True)\n\
    \    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n\
    \    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n\
    \  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f36dc63a3e0>
